const actionsType = {
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    SIGNUP_SUBMIT: "SIGNUP_SUBMIT",
    LOGIN_SUBMIT: "LOGIN_SUBMIT",
    FETCH_USERS: "FETCH_USERS",
    NO_USER_FOUND: "NO_USER_FOUND",
    ALL_COURSE: "ALL_COURSE",
    ENROLL: "ENROLL",
    LEAVE: "LEAVE"
}

export default actionsType;